{% set version = "0.4.0" %}

package:
  name: inspectrum
  version: {{ version }}

source:
  url: https://github.com/miek/inspectrum/archive/refs/tags/v{{ version }}.tar.gz
  sha256: a11214070c0aa3379e6ffd1728aa9528bf1dd722b8b72218ea1b872471b50c65
  patches:
    - 0001-Change-ssize_t-to-ptrdiff_t-for-Windows-compatibilit.patch
    - 0002-Specify-specialization-for-std-max-size_t-because-am.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - ninja
  host:
    - fftw
    - liquid-dsp
    - qt-main
    # GL headers needed for Qt on Linux
    - libgl-devel  # [linux]

test:
  requires:
    - coreutils  # [not win]
  commands:
    - QT_QPA_PLATFORM=offscreen timeout --preserve-status 10 inspectrum || [[ $? -eq 143 ]]  # [linux]
    - timeout --preserve-status 10 inspectrum || [[ $? -eq 143 ]]  # [not linux and not win]
    - start inspectrum && ping -n 10 127.0.0.1 >nul && taskkill /im inspectrum.exe /f  # [win]

about:
  home: https://github.com/miek/inspectrum
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: 'Radio signal analyser'
  description: >
    Inspectrum is a tool for analysing captured signals, primarily from software-defined radio receivers. Features include:

        - Large (100GB+) file support
        - Spectrogram with zoom/pan
        - Plots of amplitude, frequency, phase and IQ samples
        - Cursors for measuring period, symbol rate and extracting symbols
        - Export of selected time period, filtered samples and demodulated data

  dev_url: https://github.com/miek/inspectrum

extra:
  recipe-maintainers:
    - ryanvolz
