{% set version = "0.3.1" %}

package:
  name: inspectrum
  version: {{ version }}

source:
  url: https://github.com/miek/inspectrum/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 94e42333aceb06c15fb6fc10d186d61112975fdcf9539357a279e886e9edf35e

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - ninja
    # CDTs needed for GL.h for Qt
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - fftw
    - liquid-dsp
    - qt-main
    # needed for libGL for Qt
    - xorg-libxfixes  # [linux]

test:
  requires:
    - coreutils  # [not win]
  commands:
    - QT_QPA_PLATFORM=offscreen timeout --preserve-status 10 inspectrum || [[ $? -eq 143 ]]  # [linux]
    - timeout --preserve-status 10 inspectrum || [[ $? -eq 143 ]]  # [not linux and not win]
    - start inspectrum && ping -n 10 127.0.0.1 >nul && taskkill /im inspectrum.exe /f  # [win]

about:
  home: https://github.com/miek/inspectrum
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: 'Radio signal analyser'
  description: >
    Inspectrum is a tool for analysing captured signals, primarily from software-defined radio receivers. Features include:

        - Large (100GB+) file support
        - Spectrogram with zoom/pan
        - Plots of amplitude, frequency, phase and IQ samples
        - Cursors for measuring period, symbol rate and extracting symbols
        - Export of selected time period, filtered samples and demodulated data

  dev_url: https://github.com/miek/inspectrum

extra:
  recipe-maintainers:
    - ryanvolz
